#!/usr/bin/python3

import fileinput
import string

nb = 0
total = 0
cc = 0
for line in fileinput.input():
    taille = int(len(line)/2)
    
    str1 = line[0:int(taille)]
    str2 = line[-int(taille):]
    for c in str1:
        if c in str2:
            nb=0
            if c in string.ascii_lowercase:
                if(c == string.ascii_lowercase[0]):
                    total=nb +1
                while(c != string.ascii_lowercase[nb]):
                    nb +=1
                    total = nb+1
                cc+=total
                break
                
            if c in string.ascii_uppercase:
                if(c == string.ascii_uppercase[0]):
                    total=nb +1 +26
                while(c != string.ascii_uppercase[nb]):
                    nb +=1
                    total = nb+1 +26
                cc += total
                break
    
