#!/usr/bin/python3

import fileinput
import string
import time

# .........
# ......T..
# ......H..
# .........
mylist = []
i = 0

x = 0
y = 0

H = [x, y]
T = [x, y]
mapmap= [x, y]

for line in fileinput.input():
    mylist.append(line.split(' '))
    if(mylist[i][0] == 'R') :                       #droite
        if(H[1] == T[1]):
            if(H[0] < T [0] ):
                T[0] += int(mylist[i][1]) -3
            elif(H[0] > T [0] ):
                T[0] += int(mylist[i][1]) -1
            T[0] += int(mylist[i][1]) -1

        elif(H[1] > T[1]):
            T[1] += 1
            T[0] -=1
            T[0] -= int(mylist[i][1]) -2
        elif(H[1] < T[1]):
            T[1] -= 1
            T[0] +=1
            T[0] += int(mylist[i][1]) -2
        H[0] += int(mylist[i][1])
    if(mylist[i][0] == 'U') :                       #haut
        if(H[0] == T[0]):
            if(H[1] < T[1]):
                T[1] += int(mylist[i][1]) -3
            elif(H[1] > T [1] ):
                T[1] += int(mylist[i][1]) -1
            T[1] += int(mylist[i][1]) -1
        elif(H[0] > T[0]):
            T[1] += 1
            T[0] +=1
            T[1] += int(mylist[i][1]) -2
        elif (H[0] < T[0]):
            T[1] += 1
            T[0] -=1
            T[1] += int(mylist[i][1]) -2
        H[1] += int(mylist[i][1])
    if(mylist[i][0] == 'L') :                       #gauche
        if(H[1] == T[1]):
            if(H[0] < T [0] ):
                T[0] -= int(mylist[i][1]) - 1
            elif(H[0] > T [0] ):
                T[0] -= int(mylist[i][1]) -3
            T[0] -= int(mylist[i][1]) -1
        elif(H[1] > T[1]):
            T[1] += 1
            T[0] -=1
            T[0] -= int(mylist[i][1]) -2
        elif(H[1] < T[1]):
            T[1] -= 1
            T[0] -=1
            T[0] -= int(mylist[i][1]) -2
        H[0] -= int(mylist[i][1])
    if(mylist[i][0] == 'D') :                       #bas
        if(H[0] == T[0]):
            if(H[1] < T[1]):
                T[1] -= int(mylist[i][1]) -1
            elif(H[1] > T [1] ):
                T[1] -= int(mylist[i][1]) -3
            T[1] -= int(mylist[i][1]) -1
        elif(H[0] > T[0]):
            T[1] -= 1
            T[0] +=1
            T[1] -= int(mylist[i][1]) -2
        elif (H[0] < T[0]):
            T[1] += 1
            T[0] -=1
            T[1] -= int(mylist[i][1]) -2
        H[1] -= int(mylist[i][1])

    print(H ,"\t\t", T)
    i+=1
